### ISSUE TITLE
Build instruction.

### ISSUE THREAD

**Issue by jackflyer** [GwtMaterialDesign/gmd-core-demo#2]
Hi, can you add build instruction in home page readme?

**Comment by kevzlou7979** [comment]
Sure no problem

**Comment by jackflyer** [comment]
Hi, did not get update. Are planning to add soon, or it may take more time?

**Comment by kevzlou7979** [comment]
Check it here, https://github.com/GwtMaterialDesign/gmd-core-demo/blob/master/README.md

**Comment by kevzlou7979** [comment]
Also dont hesitate to test the New Demo app as it contains new features of 2.3 specially the Dark Mode.

**Comment by jackflyer** [comment]
Yup, thanks.
